# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version=v{{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - shell
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    # Repository to push the tap to.
    tap:
      owner: quackduck
      name: homebrew-tap

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/quackduck/tii"

    # Your app's description.
    # Default is empty.
    description: "Command not found? Install it right there!"
    caveats: "For bash or zsh, put something like this in a profile file (like ~/.bash_profile or ~/.zshrc):\n. #{etc}/profile.d/tii_on_command_not_found.sh"
    install: |
      bin.install "tii"
      fish_function.install "shell/tii_on_command_not_found.fish"
      (prefix/"etc/profile.d").install "shell/tii_on_command_not_found.sh"
